export const DIPLOMADOS_CATEGORIES = {
  LEGAL: "Legal y Cumplimiento",
  SEGURIDAD: "Seguridad y Cumplimiento",
  IA: "Datos e Inteligencia Artificial",
  OPERACIONES: "Operaciones y Productividad",
  LOGISTICA: "Logística y Abastecimiento",
  AMBIENTE: "Ambiente y Sostenibilidad",
  SOCIAL: "Gestión Social",
  GEOLOGIA: "Geología y Geotecnia",
  DIRECCION: "Dirección Minera",
  PROCESAMIENTO: "Procesamiento de Minerales",
  CURSOS: "Cursos Especializados"
};

export const DIPLOMADOS_LIST = [
  "CURSO DE IA DE 0 A 100",
  "DERECHO MINERO",
  "ESPECIALISTA EN COMERCIO INTERNACIONAL: GESTIÓN ADUANERA Y LOGÍSTICA",
  "GEOLOGIA MINERA",
  "GEOMETALURGIA",
  "GEOMECÁNICA SUBTERRANEA Y SUPERFICIAL",
  "GEOTECNIA MINERA",
  "GERENCIA DE SISTEMAS INTEGRADOS DE GESTION HSEQ",
  "GERENCIA ESTRATEGICA Y LIDERAZGO DE EQUIPOS EN LA MINERÍA",
  "GESTIÓN AMBIENTAL PARA EL SECTOR MINERO E INDUSTRIAL",
  "GESTIÓN DE CONTROL OPERATIVO EN PROCESOS MINEROS",
  "GESTIÓN DE OPERACIONES INDUSTRIALES",
  "GESTIÓN ESTRATÉGICA PARA EMPRESAS UTILIZANDO BIG DATA Y ANÁLISIS PREDICTIVO",
  "GESTIÓN LOGÍSTICA: COMPRAS, INVENTARIOS Y MANEJO DE PROVEEDORES",
  "GESTION LOGISTICA Y ALMACENES EN MINERIA",
  "GESTION LOGISTICA Y PROVEEDORES EN INDUSTRIA Y MINERIA",
  "GESTION MINERA",
  "LEGISLACIÓN LABORAL Y ELABORACIÓN DE PLANILLAS",
  "MINERIA 4.0 Y DIGITALIZACION MINERA",
  "PREVENCIÓN DE LA CONFLICTIVIDAD, RIESGOS SOCIALES Y RESPONSABILIDAD SOCIAL MINERA",
  "SEGURIDAD INDUSTRIAL",
  "SEGURIDAD, SALUD OCUPACIONAL EN LA INDUSTRIA Y MINERÍA",
  "SUPPLY CHAIN MANAGEMENT EN LA INDUSTRIA Y MINERÍA"
];
