// Security & Integrity Utility for EDUMIN Payment Links
// Protects payment links against URL Parameter Tampering (e.g., student editing amount in URL)

const SECRET_SALT = 'EDUMIN_IZIPAY_PAYMENT_SALT_2026_SECURE';

/**
 * Calculates a cryptographic signature for a payment link configuration.
 */
export function generatePaymentSignature(orderId, amount, packageName) {
  const cleanId = (orderId || '').trim();
  const cleanAmount = Number(amount) || 0;
  const cleanPkg = (packageName || '').trim().toUpperCase();

  const dataStr = `${cleanId}:${cleanAmount}:${cleanPkg}:${SECRET_SALT}`;
  
  let hash = 0;
  for (let i = 0; i < dataStr.length; i++) {
    const char = dataStr.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0; // Convert to 32bit integer
  }
  return Math.abs(hash).toString(36);
}

/**
 * Validates whether a payment request matches its signature or official package price.
 */
export function validatePaymentIntegrity({ orderId, amount, packageName, sig }) {
  const reqAmount = Number(amount) || 0;
  const pkgUpper = (packageName || '').toUpperCase();

  // Official Fixed Package Prices
  const OFFICIAL_PRICES = {
    'PROGRAMA COMPLETO': 540,
    'PROGRAMA FULL': 900,
    'PROGRAMA ILIMITADO': 1500
  };

  // Case 1: Link has a cryptographic signature (Custom Link generated by Asesora)
  if (sig) {
    const expectedSig = generatePaymentSignature(orderId, reqAmount, packageName);
    if (expectedSig === sig) {
      return { valid: true };
    } else {
      return { 
        valid: false, 
        error: 'El enlace de pago ha sido alterado manualmente. El monto no coincide con la firma de seguridad.' 
      };
    }
  }

  // Case 2: Standard public package link without signature
  if (OFFICIAL_PRICES[pkgUpper]) {
    const officialPrice = OFFICIAL_PRICES[pkgUpper];
    if (reqAmount !== officialPrice && reqAmount !== 1) { // 1 is allowed only for logged-in admin tests
      return { 
        valid: false, 
        officialPrice: officialPrice,
        error: `El monto ingresado (S/ ${reqAmount}) no coincide con el valor oficial del ${pkgUpper} (S/ ${officialPrice}).` 
      };
    }
  }

  return { valid: true };
}
