// Security & Integrity Utility for EDUMIN Payment Links
// Protects payment links against URL Parameter Tampering and enforces 24-hour expiration

const SECRET_SALT = 'EDUMIN_IZIPAY_PAYMENT_SALT_2026_SECURE';

/**
 * Calculates a cryptographic signature for a payment link configuration.
 */
export function generatePaymentSignature(orderId, amount, packageName, exp = '') {
  const cleanId = (orderId || '').trim();
  const cleanAmount = Number(amount) || 0;
  const cleanPkg = (packageName || '').trim().toUpperCase();
  const cleanExp = exp ? String(exp).trim() : '';

  const dataStr = `${cleanId}:${cleanAmount}:${cleanPkg}:${cleanExp}:${SECRET_SALT}`;
  
  let hash = 0;
  for (let i = 0; i < dataStr.length; i++) {
    const char = dataStr.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0; // Convert to 32bit integer
  }
  return Math.abs(hash).toString(36);
}

/**
 * Validates whether a payment request matches its signature or official package price, and checks 24h expiration.
 */
export function validatePaymentIntegrity({ orderId, amount, packageName, sig, exp }) {
  const reqAmount = Number(amount) || 0;
  const pkgUpper = (packageName || '').toUpperCase();

  // Official Fixed Package Prices
  const OFFICIAL_PRICES = {
    'PROGRAMA COMPLETO': 540,
    'PROGRAMA FULL': 900,
    'PROGRAMA ILIMITADO': 1500
  };

  // Case 1: Link has a cryptographic signature (Custom Link generated by Asesora)
  if (sig) {
    const expectedSig = generatePaymentSignature(orderId, reqAmount, packageName, exp);
    if (expectedSig !== sig) {
      return { 
        valid: false, 
        error: 'El enlace de pago ha sido alterado manualmente o la firma de seguridad no coincide.' 
      };
    }

    // Check 24-hour expiration if exp timestamp is present
    if (exp) {
      const expTime = Number(exp);
      const now = Date.now();
      if (!isNaN(expTime) && now > expTime) {
        const expiredDateStr = new Date(expTime).toLocaleString('es-PE', {
          day: '2-digit',
          month: '2-digit',
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        });
        return { 
          valid: false, 
          isExpired: true,
          error: `⏱️ ENLACE DE PAGO CADUCADO:\n\nEste enlace de pago personalizado venció el ${expiredDateStr} (Validez máxima de 24 horas).\n\nPor favor solicita un nuevo enlace oficial a tu asesora de EDUMIN.` 
        };
      }
    }

    return { valid: true };
  }

  // Case 2: Standard public package link without signature
  if (OFFICIAL_PRICES[pkgUpper]) {
    const officialPrice = OFFICIAL_PRICES[pkgUpper];
    if (reqAmount !== officialPrice && reqAmount !== 1) { // 1 is allowed only for logged-in admin tests
      return { 
        valid: false, 
        officialPrice: officialPrice,
        error: `El monto ingresado (S/ ${reqAmount}) no coincide con el valor oficial del ${pkgUpper} (S/ ${officialPrice}).` 
      };
    }
  }

  return { valid: true };
}

